# Generated by Django 5.1.5 on 2025-01-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resident_id', models.CharField(max_length=20, unique=True)),
                ('resident_type', models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Staff', 'Staff')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuarantineRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Symptom_Status.resident')),
            ],
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Infected', 'Infected')], max_length=10)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Symptom_Status.resident')),
            ],
        ),
    ]
