# Generated by Django 5.1.5 on 2025-01-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
