# Generated by Django 5.1.5 on 2025-01-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0002_hotspot_latitude_hotspot_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspot',
            old_name='location_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='hotspot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='infected_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='recovered_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
