# Generated by Django 5.1.5 on 2025-01-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termsandconditions',
            old_name='updated_at',
            new_name='last_updated',
        ),
    ]
