# Generated by Django 5.1.5 on 2025-01-30 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='residenthealthstatus',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='room',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residenthealthstatus',
            name='original_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previously_assigned', to='hostels.room'),
        ),
    ]
