# Generated by Django 5.1.3 on 2024-12-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eHealthSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='resident',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eHealthSystem.block'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eHealthSystem.level'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eHealthSystem.block')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eHealthSystem.level')),
            ],
        ),
        migrations.AlterField(
            model_name='resident',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eHealthSystem.room'),
        ),
    ]
