# Generated by Django 5.1.3 on 2024-12-11 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eHealthSystem', '0002_block_level_alter_resident_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
