# Generated by Django 5.1.3 on 2024-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eHealthSystem', '0003_alter_resident_user_alter_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('block', 'level', 'number')},
        ),
    ]
