# Generated by Django 5.1.5 on 2025-01-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_room_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_occupied',
        ),
    ]
