# Generated by Django 5.1.4 on 2024-12-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_infectedperson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectedperson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
